version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0

jobs:
  backend-build:
    docker:
      - image: circleci/node:10
    working_directory: ~/circleci-test/backend
    steps:
      - checkout
          path: ~/circleci-test
      - run:
          name: Navigate to backend
          command: cd backend
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Backend
          command: yarn build

workflows:
  build-and-deploy:
    jobs:
      - backend-build
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: ${AWS_ERC_REPO}
          region: AWS_REGION
          tag: ${CIRCLE_SHA1}
          requires:
            - backend-build
